development:
  api_key: development_api_key
  list_id: generic_list_id
  monkey_list_id: monkey_list_id

production:
  api_key: <%= 'production_api' + '_key' %>
  list_id: generic_list_id
  monkey_list_id: monkey_list_id
